[package]
name = "rust_ev_crypto_primitives"
description = "Crypto Primitives necessary for E-Voting Applications."
authors = ["Denis Morel"]
version = "0.5.0"
edition = "2021"
rust-version = "1.74"
license = "LGPL-3.0+"
repository = "https://github.com/de-mo/rust_ev_crypto_primitives"
readme = "README.md"
tegories = ["cryptography", "mathematics"]
keywords = ["math", "e-voting", "crypto"]

[dependencies]
openssl-sys = "0.9"
openssl = "0.10"
chrono = "0.4"
thiserror = "1.0"
data-encoding = "2.5"
num-traits = "0.2"
anyhow = "1.0"

# Dependencies for usage with rug
rug = {version="1.24", optional=true}
rug-miller-rabin = {version="0.1", optional=true}

# Dependencies for usage with num-bigint
miller_rabin = {version = "1.1.1", optional = true}
num-bigint = {version = "0.4", optional = true}

[features]
default=["rug"]
num-bigint=["dep:miller_rabin", "dep:num-bigint"]
rug=["dep:rug", "dep:rug-miller-rabin"]
checks=[]
